const Coverapi = [
  {
    id: 1,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },

  {
    id: 2,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 3,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 4,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 4,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 4,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 5,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 6,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 7,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 8,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 9,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 10,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 11,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 12,
    cover_image1:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/cases-covers/back-cover/o/t/o/zap-space-rm12prop5g-zapcase-original-imahyvpsfqufzk2s.jpeg?q=70",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "908",
    dicount_price: "460",
    title: "Best Quality mobile covers",
  },
  {
    id: 13,
    cover_image1:
      "https://img.freepik.com/premium-photo/collection-phone-case-elegance-with-lavish-glamorous-designs-luxury-styles-mockup_655090-540207.jpg?w=740",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "990",
    dicount_price: "760",
    title: "red Color i Phone covers",
  },
  {
    id: 14,
    cover_image1: "https://m.media-amazon.com/images/I/71YTXEFF5ZL._SX679_.jpg",
    cover_image2: "",
    cover_image3: "",
    category: "",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    total_price: "489",
    dicount_price: "389",
    title: "Pink Colored Iphone 15 Pro MaxCovers",
  },
];

export default Coverapi;
